# Generated by Django 5.2.15 on 2026-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_anthropic_api_key_profile_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_theme',
            field=models.CharField(default='retrowave', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='unlocked_themes',
            field=models.CharField(default='retrowave', help_text='Comma-separated theme keys this user has unlocked.', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
