# Generated by Django 5.2.15 on 2026-06-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_profile_active_theme_profile_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points_awarded',
        ),
    ]
