# Generated by Django 5.2.15 on 2026-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('gemini', 'Google Gemini')], default='openai', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
