# Generated by Django 5.2.15 on 2026-06-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_profile_ai_provider_profile_gemini_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (ChatGPT)'), ('gemini', 'Google Gemini'), ('local', 'Local model (no API key, no cost)')], default='openai', max_length=10),
        ),
    ]
